server:
  port: 9000
  servlet:
    session:
      cookie:
        name: UISESSION
spring: 
  application:
    name: quotation-back-office
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://172.104.178.178:3306/adsplus.auth?verifyServerCertificate=false&useSSL=false&characterEncoding=utf8
#    password: root
    jdbcUrl: jdbc:mysql://localhost:3306/adsplus.auth?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    password: huong20031999
    username: root

    tomcat:
      max-wait: 20000
      max-active: 5
      max-idle: 20
      min-idle: 15
      
  warehouse-datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://172.104.178.178:3306/adsplus.data.warehouse?verifyServerCertificate=false&useSSL=false&characterEncoding=utf8
#    password: root
    jdbcUrl: jdbc:mysql://localhost:3306/adsplus.data.warehouse?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    password: huong20031999
    username: root
#    jdbcUrl: jdbc:mysql://139.162.8.209:3306/adsplus.data.warehouse?verifyServerCertificate=false&useSSL=false&characterEncoding=utf8
#    password: oP?K28+cNR.(
#    username: root
    tomcat:
      max-wait: 20000
      max-active: 5
      max-idle: 20
      min-idle: 15

google:
  app:
    id: 811332325629-8ecokuda8688m3ef0tufqtjfp0b4tgok.apps.googleusercontent.com
    secret: 2CcI3X4n7h13uu8nqGuGQaD4
  redirect:
    uri: http://localhost:9000/login-google
#    uri: http://staging.adstech.vn:9000/login-google
  link:
    get:
      token: https://accounts.google.com/o/oauth2/token
      authen: https://accounts.google.com/o/oauth2/auth
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?access_token=
      
logging:
  level:
    com.zaxxer.hikari: debug
      
    